apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vovudn/gitops.git
    targetRevision: main
    path: k8s-monitoring
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
